server:
  port: ${PORT:8087}

spring:
  application:
    name: notification-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
