server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nexushr
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379

nexushr:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    issuer: NexusHR
