CREATE TABLE IF NOT EXISTS roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS permissions (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id INT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id INT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    reset_token VARCHAR(255),
    reset_token_expiry TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id INT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token VARCHAR(512) NOT NULL UNIQUE,
    expiry_date TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    ip_address VARCHAR(45),
    user_agent VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed Permissions
INSERT INTO permissions (name) VALUES 
('EMPLOYEE_READ'), ('EMPLOYEE_CREATE'), ('EMPLOYEE_UPDATE'), ('EMPLOYEE_DELETE'),
('ATTENDANCE_READ'), ('ATTENDANCE_MANAGE'), ('LEAVE_REQUEST'), ('LEAVE_APPROVE'),
('PAYROLL_READ'), ('PAYROLL_PROCESS'), ('PERFORMANCE_MANAGE'), ('AI_INSIGHTS_VIEW'),
('REPORT_EXPORT'), ('USER_MANAGE')
ON CONFLICT (name) DO NOTHING;

-- Seed Roles
INSERT INTO roles (name) VALUES 
('SUPER_ADMIN'), ('HR_ADMIN'), ('HR_MANAGER'), ('MANAGER'), ('EMPLOYEE'), ('PAYROLL_ADMIN'), ('PERFORMANCE_MANAGER')
ON CONFLICT (name) DO NOTHING;
