apiVersion: v1
kind: Secret
metadata:
  name: nexushr-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_PASSWORD: "{{ "{{" }} .Values.database.password | default \"CHANGEME_DB_PASSWORD\" {{ "}}" }}"
  JWT_SECRET: "{{ "{{" }} .Values.jwt.secret | default \"CHANGEME_JWT_SECRET\" {{ "}}" }}"
